apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-db-deployment
  namespace: sample-db
spec:
  selector:
    matchLabels:
      app: sample-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-db
    spec:
      containers:
        - name: map-db-container
          image: sham6/sample-mysql:1.0 # docker-hubのリポジトリを指定
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql_root_password
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: db-pvc
